openapi: 3.0.2
info:
  title: ID Generator
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  /ids:
    get: 
      responses:
        '200':
          description: Request otp success
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/Id'
components:
  schemas:
    Id:
      type: string